### ISSUE TITLE
Add nuget package for core files

### ISSUE THREAD

**Issue by skttl** [skttl/umbraco-doc-type-grid-editor#135]
Would be nice to have a nuget package for just the core dlls.

**Comment by stefankip** [comment]
I agree, could use that right now. I have a Core project where the Controllers are situated and need a reference for the type `DocTypeGridEditorSurfaceController`.

**Comment by stefankip** [comment]
So did this happen? Or...?

**Comment by skttl** [comment]
No, with the coming release of the Block Editor, my expectation is that DTGE will be obsolete, and I don't want to invest the time in adding this then :)

Happy to merge a PR :)

**Comment by stefankip** [comment]
Just curious what the reason was for closing this :-) Because I didn't see any comment I didn't know why it was closed.

You mention the coming release of the Block Editor, do you have a source which states the release will be soon? Because AFAIK they didn't start building yet:

From: https://github.com/umbraco/rfcs/pull/12#issuecomment-527046806
"we'll let you know once we start POC work and implementation."

And then nothing is mentioned about this POC ;-)

**Comment by skttl** [comment]
Coming up in 8.7:  https://umbraco.com/blog/product-update-may-29th-2020/

My guess would be that the grid is not part of the first iteration, but the
block editor should enable you to do your own "block editor", and then also
a grid like editor. Which I might do :)





Den fre. 5. jun. 2020 kl. 09.31 skrev Stefan Kip <notifications@github.com>:

**Comment by stefankip** [comment]
Check, didn't notice the blog post yet, thanks :-)
