### ISSUE TITLE
No Session in Http Context

### ISSUE THREAD

**Issue by zharonar** [skttl/umbraco-doc-type-grid-editor#214]
Through `HttpContextBase` or `UmbracoContext`, session is always null. Is there any workaround to get session from Umbraco CMS when using docTypeGridEditor?

**Comment by skttl** [comment]
Hi @zharonar is this when the previews are rendering, or when the frontend of the website is rendering?

**Comment by skttl** [comment]
Hi again @zharonar 

Just tried adding `Session["hello"] = "HELLO";` to my layout view, and then `<div class="text-4xl">@Session["hello"]</div>` to one of my DTGE partials. And that worked fine.

![image](https://user-images.githubusercontent.com/3726467/92517528-180e9580-f217-11ea-9039-e2071e4808fc.png)

So I suspect your are missing the Session in the previews? Whats your usecase for that?

**Comment by zharonar** [comment]
Hey @skttl , thanks for replying fast! This happens only when I am at the preview, I have a lot of Session uses in my backcode, controllers etc., and when I'm at preview tones of exceptions occurred and I was wondering what was it and how to get session from preview.

**Comment by skttl** [comment]
Thanks, the session is unavailable in the previews because they are running on an Api Controller, which doesn't have access to the session.

It would be a breaking change to change that, and I don't really see the benefit of having session data in previews.

You can always null check you Session variables and show something else if they don't exist. Or create another view for previewing.
