### ISSUE TITLE
Umbraco 9?

### ISSUE THREAD

**Issue by drbldgtl** [skttl/umbraco-doc-type-grid-editor#248]
Is there a plan to create an Umbraco 9 version of this package?

**Comment by skttl** [comment]
Yes 🎉

**Comment by skttl** [comment]
https://github.com/skttl/umbraco-doc-type-grid-editor-core

**Comment by skttl** [comment]
https://github.com/skttl/umbraco-doc-type-grid-editor/tree/dev-v9

**Comment by cleversolutions** [comment]
Thanks @skttl your awesome!!

**Comment by skttl** [comment]
(First) beta is out, https://www.nuget.org/packages/Our.Umbraco.DocTypeGridEditor/9.0.0-beta001

Give it a spin :)

**Comment by SpinboxPaul** [comment]
Why is the advice to not use this for new projects?
![image](https://user-images.githubusercontent.com/54625085/145422413-2943ad0c-b293-4fd5-9a77-f8fa0b2228a9.png)

**Comment by cleversolutions** [comment]
I'm not the maintainer, but I would venture it's because Block List does everything Grid and DTGE does and more, and is built into Umbraco :) At some point we will have to write migrations from Grid/DTGE to Block List. I don't think it should be hard to do, I've already done that from LeBlender to DTGE for all of the sites we migrated from V7 to V8. @skttl did us all a huge favour and gave us more time before we have to migrate sites off of Grid. @skttl want to build us a slick tool to do that migration :)

**Comment by skttl** [comment]
@SpinboxPaul it says in the text. It is only intended to let you upgrade your existing 7/8 projects without having to rethink grid usage for now.

In the near future Umbraco will ship with a new backoffice, and possibly other breaking changes that will affect DTGE. And since I don't think the current Grid editor is a good choice anymore, I'm not going to do a rewrite once the backoffice hits.

So it's basically just a heads up - you can use it for shortlived projects, or only if you prepare for possible migrations to other editors.
